spring:
  jpa:
    hibernate:
      ddl-auto: ${PLAN}
    properties:
      hibernate:
        default_batch_fetch_size: ${BATCH_SIZE}
        show_sql: ${VALUE}
        format_sql: ${VALUE}
    open-in-view: ${VALUE}
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}

  flyway:
    enabled: ${VALUE}
    baseline-on-migrate: ${VALUE}

server:
  port: ${PORT}
